# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Omegat - The Free Open-Source Translation Memory Tool
email: contact@omegat.org
description: > # this means to ignore newlines until "baseurl:"
  OmegaT is a free open-source translation memory application written in Java.
  It is a tool intended for professional translators.

# the subpath of your site, e.g. /blog
baseurl: ""

# the base hostname & protocol for your site, e.g. http://example.com
url: "http://omegat.org"
baseurl: ""

# Github
#url: "https://omegat-org.github.io"
#baseurl: "/omegat-website"

# Used by the jekyll-seo-tag plugin
logo: http://omegat.org/img/omegat_96.png
twitter:
  username: OmegaTOfficial
#facebook:
#  app_id:
#  publisher:
#  admins:
social:
  name: OmegaT
  links:
    - https://sourceforge.net/projects/omegat/
    - https://github.com/omegat-org/
    - https://twitter.com/OmegaTOfficial
    - https://www.facebook.com/OmegaTOfficial

google_analytics: UA-87327-16

# i18n plugin
languages: [ "en" , "fr" ,"ar", "ca", "cz", "de", "el", "es", "gl", "id", "ia", "it", "ko", "hu", "ja", "nl", "pl", "br", "pt", "ru", "sq", "sk", "si", "hr", "fi", "sv", "zh_CN", "zh_TW", "en" ]
exclude_from_localizations: ["LICENSE", "feed.xml", "sitemap.xml", "robots.txt", "js", "fonts", "img", "css", "favicon.png", "tutorial", "omegatk", "files", "CNAME", "android-chrome-192x192.png", "android-chrome-256x256.png", "apple-touch-icon.png", "favicon-16x16.png", "favicon-32x32.png", "mstile-150x150.png", "safari-pinned-tab.svg", "favicon.ico", "manifest.json", "browserconfig.xml", "assets" ]

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

assets:
  digest: false

gems:
  - uglifier
  # https://github.com/jekyll/jekyll-assets
  - jekyll-assets
  - jekyll-sitemap
  #- jekyll-feed
  # https://github.com/Anthony-Gaudino/jekyll-multiple-languages-plugin
  - jekyll-multiple-languages-plugin

exclude:
  - README
  - LICENSE
  - Gemfile
  - Gemfile.lock
