name: run Jekyll build for test

on:
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Ž
        uses: actions/checkout@v4
      - name: Setup Ruby ðŸ’Ž
        uses: ruby/setup-ruby@4a9ddd6f338a97768b8006bf671dfbad383215f4
        with:
          ruby-version: "3.2.6"
          bundler-cache: true
          cache-version: 0
      - name: Setup Pages ðŸ“ƒ
        id: pages
        uses: actions/configure-pages@v5
      - name: Install HTML Proofer ðŸ”§
        run: gem install html-proofer
      - name: Build with Jekyll ðŸ—
        id: jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: development
      - name: Check for broken links ðŸ§ðŸ”—
        id: links
        run: htmlproofer --log-level :debug _site 2> links.log
        continue-on-error: true
      - name: Archive checker log ðŸ—„
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: links-check.log
          path: links.log
      - name: Upload artifact ðŸšš
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: _site
      - name: Report result
        if: ${{ steps.jekyll.outcome == 'failure' || steps.links.outcome == 'failure' }}
        run: exit 1
