name: run Jekyll build for test

on:
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@v4
      - name: Setup Ruby ğŸ’
        uses: ruby/setup-ruby@4a9ddd6f338a97768b8006bf671dfbad383215f4
        with:
          ruby-version: "3.2.6"
          bundler-cache: true
          cache-version: 0
      - name: Setup Pages ğŸ“ƒ
        id: pages
        uses: actions/configure-pages@v5
      - name: Build with Jekyll ğŸ—
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: development
      - name: Upload artifact ğŸšš
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: _site
