# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Check Jekyll output is unchanged

on:
  # Runs on any pull request
  pull_request:

# Cancel previous builds for this branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Test job
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target branch ğŸ›
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}

      - name: Setup Ruby ğŸ’
        uses: ruby/setup-ruby@4a9ddd6f338a97768b8006bf671dfbad383215f4
        with:
          ruby-version: "2.7.6" # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems

      - name: Patch jekyll/assets/utils.rb ğŸ§·
        run: patch --verbose vendor/bundle/ruby/2.7.0/gems/jekyll-assets-3.0.12/lib/jekyll/assets/utils.rb _patch_multiple-language/jekyll_assets_utils.patch

      - name: Build with Jekyll from target branch ğŸ—
        # Outputs to the './_site' directory by default
        run: bundle exec jekyll build
        # env:
        #   JEKYLL_ENV: production

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Get Node Dependencies
        run: npm ci

      - name: Get snapshots from target branch
        run: npm run update-snapshots

      - name: Remove site directory
        run: npm run clean

      - name: Checkout PR branch ğŸ›
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Publish Snapshots
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: snapshots
          path: __tests__/__snapshots__/snapshots.test.js.snap

      - name: Get Ruby dependencies
        # This is needed to get the gems from the PR branch
        run: bundle install

      - name: Build with Jekyll from PR branch ğŸ—
        # Outputs to the './_site' directory by default
        run: bundle exec jekyll build

      - name: Snapshot Testing
        run: npm run test-with-output

      - name: Publish Snapshot Test Results
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: snapshot-test-results
          path: snapshot-test-results.json
