# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Check Jekyll output is unchanged

on:
  # Runs on any pull request
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Cancel previous builds for this branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Test job
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@v4

      - name: Setup Ruby ğŸ’
        uses: ruby/setup-ruby@4a9ddd6f338a97768b8006bf671dfbad383215f4
        with:
          ruby-version: "2.7.6" # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems

      - name: Patch jekyll/assets/utils.rb ğŸ§·
        run: patch --verbose vendor/bundle/ruby/2.7.0/gems/jekyll-assets-3.0.12/lib/jekyll/assets/utils.rb _patch_multiple-language/jekyll_assets_utils.patch

      - name: Build with Jekyll ğŸ—
        # Outputs to the './_site' directory by default
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Snapshot Testing
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: npm ci
      - run: npm test
