# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Test workflow for building a Jekyll site
name: Test build of Jekyll site

on:
  # Runs on any pull request
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Ž
        uses: actions/checkout@v4

      - name: Setup Ruby ðŸ’Ž
        uses: ruby/setup-ruby@4a9ddd6f338a97768b8006bf671dfbad383215f4
        with:
          ruby-version: "2.7.6" # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems

      #- name: Install HTML Proofer ðŸ”§
      #  run: gem install html-proofer

      - name: Patch jekyll/assets/utils.rb ðŸ§·
        run: patch --verbose vendor/bundle/ruby/2.7.0/gems/jekyll-assets-3.0.12/lib/jekyll/assets/utils.rb _patch_multiple-language/jekyll_assets_utils.patch

      - name: Build with Jekyll ðŸ—
        # Outputs to the './_site' directory by default
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      #- name: Check for broken links ðŸ§ðŸ”—
      #  run: htmlproofer --log-level :debug _site 2> links.log
      #  continue-on-error: true

      #- name: Archive checker log ðŸ—„
      #  uses: actions/upload-artifact@v1
      #  with:
      #    name: links-check.log
      #    path: links.log

      - name: Upload artifact ðŸšš
        # Automatically uploads an artifact from the './_site' directory by default
        uses: actions/upload-pages-artifact@v3
